#!/usr/bin/env python3
# src/scribe/pr_hook_script.py

import sys
import os
from scribe.git_utils import parse_git_diff
from scribe.pull_request_utils import get_pull_request_info, get_pull_request_diff
from scribe.config import get_model_config
from scribe.plugins import get_plugin

def main():
    # The PR number is passed as the first argument
    pr_number = sys.argv[1]

    try:
        base_branch, head_branch, commit_messages = get_pull_request_info(pr_number)
        diff = get_pull_request_diff(base_branch, head_branch)
        diff_summary = parse_git_diff(diff)

        # Get the model configuration
        config = get_model_config()
        # Get the appropriate plugin
        plugin = get_plugin(config)

        # Generate pull request description
        pr_description = plugin.generate_pull_request_message(diff_summary, commit_messages)

        print(f"# Generated by ZScribe using {config['model']}\n")
        print(pr_description)
        print("\n# Please review and edit the pull request description as needed.")

    except Exception as e:
        print(f"Error generating pull request description: {e}")
        print("Please write your pull request description manually.")

if __name__ == "__main__":
    main()